import importlib

agent = importlib.import_module("challenges.05.agent")

# A brand new edge case example
test_query = "Jupiter has a mass of 1898 x 10^24 kg, while Saturn has a mass of 568 x 10^24 kg. Which planet is lighter?"

print("\n--- Testing New Example ---")
print(f"Query: {test_query}")

# Execute the modular agent exactly as the API does
raw_output = agent.run(test_query)

print("\n--- Raw String Output Generated by LLM ---")
print(f"--> '{raw_output}' <--")

# Apply the API post-processing to show the final exact string
final_output = raw_output.strip().strip('.').strip('"').strip("'").strip()
print("\n--- Final Cleaned Output (Sent to Evaluator) ---")
print(f"--> '{final_output}' <--\n")
